### ISSUE TITLE
bug text.cpp

### ISSUE THREAD

**Issue by TankyThunderpaw** [mikyll/Fondamenti-di-Computer-Graphics-M#3]
when calling updateText on a text object previously created with an empty string an "_Xout_of_range" exception is thrown

lines of code involved:
https://github.com/mikyll/Fondamenti-di-Computer-Graphics-M/blob/main/laboratorio/02es/text.cpp#L570-L608

**Comment by mikyll** [comment]
Lines that are causing the issue: [595-597 from text.cpp](https://github.com/mikyll/Fondamenti-di-Computer-Graphics-M/blob/5c93d314b45168bc210c7afd2193bdfe70bac861/laboratorio/02es/text.cpp#L595-L597)

```cpp
float widthLines = text->figures.at(0).widthLines;
float sizePoints = text->figures.at(0).sizePoints;
text->figures.clear();
```

There's no check on the size of the vector, before getting those 2 values.

Possible solutions:
- add the `widthLines` and `sizePoints`fields to `Text` structure;
- (ugly) check the size of the vector and if it's empty, use default values for `widthLines` and `sizePoints`;
- (ugly) add a `scale` field;
- (workaround) check the size and return immediately, if the vector is empty (but that would break the behaviour of the function);

**Comment by mikyll** [comment]
To experience the issue:
1. pass an empty string to `createText()` function at [**line 199** in ui.cpp](https://github.com/mikyll/Fondamenti-di-Computer-Graphics-M/blob/f5b0ef2bbd44c8380dc87deb7b7cdf4c22aa879d/laboratorio/02es/ui.cpp#L199) to:
```c
  textInvulnerabilityTimeLeft = createText(170, 50, false, TEXT_SCALE / 2, true, "");
```
2. Start the game
3. Exception thrown:
```lang-none
Exception thrown at 0x00007FFDBF42CF19 in 02es.exe: Microsoft C++ exception: std::out_of_range at memory location 0x00000065799AF540.
Unhandled exception at 0x00007FFDBF42CF19 in 02es.exe: Microsoft C++ exception: std::out_of_range at memory location 0x00000065799AF540.
```
